Repository tteokguk-please/tteokguk-frontend, pull requests merged in 2024-01, with the labels that each got.

#2 [#1] Chore: 프로젝트 세팅
  .eslintrc.cjs
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  .nvmrc
  .prettierrc
  README.md
  index.html
  package.json
  panda.config.ts
  pnpm-lock.yaml
  postcss.config.cjs
  src/App.tsx
  src/index.css
  src/main.tsx
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: ⚙ Chore

#6 [#5] Feat: 폰트, 컬러 변수, 이미지들 추가
  index.html
  panda.config.ts
  src/assets/images/header-logo.png
  src/assets/images/home-logo.png
  src/assets/images/tteokguk-complete.png
  src/assets/images/tteokguk-incomplete.png
  src/assets/svg/activity.svg
  src/assets/svg/before.svg
  src/assets/svg/check.svg
  src/assets/svg/dumpling.svg
  src/assets/svg/fish-bread.svg
  src/assets/svg/material.svg
  src/assets/svg/no-check.svg
  src/assets/svg/profile.svg
  src/assets/svg/talk.svg
  src/assets/svg/visit.svg
  src/assets/svg/wish.svg
  src/index.css
Labels: ✨ Feature

#4 [#3] Feat: 라우터 설정
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/constants/route.ts
  src/pages/EmailLoginPage.tsx
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/pages/MyActivityPage.tsx
  src/pages/MyPage.tsx
  src/pages/NotFoundPage.tsx
  src/pages/RandomUserPage.tsx
  src/pages/SignupPage.tsx
  src/pages/TteokgukCookingPage.tsx
  src/pages/TteokgukPage.tsx
  src/routes/Link.tsx
  src/routes/Routes.tsx
  src/routes/useNavigate.tsx
Labels: ✨ Feature

#8 [#7] Feat: 공통 스타일을 담당하는 버튼, 모달 컴포넌트와 레이아웃 구현
  .eslintrc.cjs
  package.json
  panda.config.ts
  pnpm-lock.yaml
  src/App.tsx
  src/assets/svg/close.svg
  src/components/common/Button.tsx
  src/components/common/IconButton.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/ModalBody.tsx
  src/components/common/modal/ModalHeader.tsx
  src/components/layout/Layout.tsx
  src/constants/route.ts
  src/main.tsx
  src/pages/LoginPage.tsx
  src/routes/Routes.tsx
Labels: ✨ Feature

#11 [#9] Feat: 홈 페이지, 로그인 페이지 UI 구현
  src/components/common/Button.tsx
  src/components/common/Header.tsx
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/routes/useNavigate.tsx
  src/routes/useRouter.tsx
Labels: ✨ Feature

#13 [#12] Feat: 개인정보 수집 및 마케팅 활용 동의 모달, 회원가입시 환영 모달, 떡국 재료 추가 모달 UI 구현
  src/assets/svg/dumpling.svg
  src/components/Signup/PrivacyAndMarketingAgreementModal.tsx
  src/components/common/Button.tsx
  src/components/common/Header.tsx
  src/components/common/IconButton.tsx
  src/components/common/Input.tsx
  src/components/common/Label.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/ModalBody.tsx
  src/components/common/modal/ModalHeader.tsx
  src/components/shared/AddIngredientsModal.tsx
  src/components/shared/CheerMessageModal.tsx
  src/components/shared/CheerSuccessModal.tsx
  src/components/shared/GuideModal.tsx
  src/components/shared/WelcomModal.tsx
Labels: ✨ Feature

#18 [#16] Feat: 마이 페이지 UI 구현
  src/components/Mypage/IngredientList.tsx
  src/components/Mypage/IngredientListItem.tsx
  src/components/Mypage/TteokgukList.tsx
  src/components/Mypage/TteokgukListItem.tsx
  src/components/common/IconButton.tsx
  src/pages/MyPage.tsx
Labels: ✨ Feature

#17 [#14] Feat: 메인 페이지 UI 구현
  package.json
  panda.config.ts
  pnpm-lock.yaml
  src/components/common/Tteokguks/TteokgukCard.tsx
  src/components/common/Tteokguks/TteokgukList.tsx
  src/pages/MainPage.tsx
Labels: ✨ Feature

#23 [#20] Feat: 떡국 페이지 UI 구현
  src/components/common/Ingredient.tsx
  src/pages/TteokgukPage.tsx
Labels: ✨ Feature

#25 [#10] Feat: 이메일로 로그인 페이지 UI 구현
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/assets/svg/guide.svg
  src/components/common/Button.tsx
  src/components/common/IconButton.tsx
  src/components/common/Input.tsx
  src/components/common/ToastContainer.tsx
  src/index.css
  src/pages/EmailLoginPage.tsx
Labels: ✨ Feature

#22 [#21] Feat: 다른 유저 페이지 UI 구현
  src/components/MyActivityPage/ReceivedIngredientsList.tsx
  src/components/MyActivityPage/ReceivedIngredientsListItem.tsx
  src/components/common/Header.tsx
  src/components/common/TteokgukList.tsx
  src/components/common/TteokgukListItem.tsx
  src/components/common/UserProfileSection.tsx
  src/components/layout/Layout.tsx
  src/pages/MyActivityPage.tsx
  src/pages/RandomUserPage.tsx
  src/routes/Routes.tsx
Labels: ✨ Feature

#26 [#15] Feat: 떡국 만들기 페이지 UI 구현
  src/index.css
  src/pages/TteokgukCookingPage.tsx
Labels: ✨ Feature

#27 [#19] Feat: 활동 내역 페이지 UI 구현
  src/components/common/Tteokguks/TteokgukList.tsx
  src/index.css
  src/pages/MainPage.tsx
  src/pages/MyActivityPage.tsx
Labels: ✨ Feature

#31 [#28] Feat: 회원가입 페이지 UI 구현
  .husky/commit-msg
  package.json
  pnpm-lock.yaml
  src/components/Signup/SignupForm.tsx
  src/components/common/Button.tsx
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/pages/SignupPage.tsx
  src/types/form/signup.ts
  src/types/utils.ts
Labels: ✨ Feature

#30 [#29] Feat: ky를 사용하여 api core 로직 구현
  src/apis/core.ts
  src/utils/localStorage.ts
Labels: ✨ Feature

#38 [NO-ISSUE] Modify: 모달 close 관련 핸들러 네이밍 수정
  src/components/Signup/PrivacyAndMarketingAgreementModal.tsx
  src/components/common/modal/ModalHeader.tsx
  src/components/shared/AddIngredientsModal.tsx
  src/components/shared/CheerMessageModal.tsx
  src/components/shared/CheerSuccessModal.tsx
  src/components/shared/GuideModal.tsx
  src/components/shared/WelcomModal.tsx
Labels: ✏️ Modify

#40 [#34] Feat: 회원가입 API 연동
  panda.config.ts
  src/apis/auth.ts
  src/components/Signup/SignupForm.tsx
  src/components/common/Button.tsx
  src/components/common/modal/Modal.tsx
  src/components/shared/WelcomModal.tsx
  src/constants/ingredient.ts
  src/pages/LoginPage.tsx
  src/pages/SignupPage.tsx
  src/store/auth.ts
  src/types/auth.ts
  src/types/ingredient.ts
  src/types/utils.ts
Labels: ✨ Feature

#43 [#42] Chore: vercel rewrites 추가
  vercel.json
Labels: ⚙ Chore

#36 [#33] Feat: 닉네임 설정 페이지 UI 구현
  src/components/Signup/SignupForm.tsx
  src/pages/NicknamePage.tsx
  src/routes/Routes.tsx
Labels: ✨ Feature

#35 [#32] Feat: 활동 내역의 "내가 응원한 떡국" 탭 UI 적용 및 메인 페이지 스크롤 제어 추가
  package.json
  pnpm-lock.yaml
  src/components/MyActivityPage/ReceivedIngredientsList.tsx
  src/components/MyActivityPage/ReceivedIngredientsListItem.tsx
  src/components/Mypage/TteokgukList.tsx
  src/components/Mypage/TteokgukListItem.tsx
  src/components/Signup/SignupForm.tsx
  src/components/common/Header.tsx
  src/components/common/ReceivedIngredientsList.tsx
  src/components/common/TteokgukList.tsx
  src/components/common/TteokgukListItem.tsx
  src/components/common/TteokgukWithCaptionList.tsx
  src/components/common/Tteokguks/TteokgukList.tsx
  src/index.css
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/pages/MyActivityPage.tsx
  src/pages/MyPage.tsx
  src/pages/RandomUserPage.tsx
  src/pages/TteokgukCookingPage.tsx
  src/pages/TteokgukPage.tsx
Labels: ✨ Feature

#46 [#45] 배포 워크플로우 구현
  .github/workflows/deploy-resource.yml
Labels: ✨ Feature

#52 [NO-ISSUE] Modify: 패키지 매니저 변경 및 노드 버전 설정
  .github/workflows/deploy-resource.yml
Labels: ✏️ Modify

#53 [NO-ISSUE] Modify: deploy workflows 내 Install pnpm 순서 변경
  .github/workflows/deploy-resource.yml
Labels: ✏️ Modify

#44 [#37] Feat: 소원 떡국 생성 api 구현
  src/apis/auth.ts
  src/apis/tteokguk.ts
  src/assets/svg/dumpling.svg
  src/assets/svg/ingredients/beef.svg
  src/assets/svg/ingredients/candy.svg
  src/assets/svg/ingredients/dumpling.svg
  src/assets/svg/ingredients/egg.svg
  src/assets/svg/ingredients/fish-cake.svg
  src/assets/svg/ingredients/garlic.svg
  src/assets/svg/ingredients/green-onion.svg
  src/assets/svg/ingredients/index.ts
  src/assets/svg/ingredients/mushroom.svg
  src/assets/svg/ingredients/rice-cake.svg
  src/assets/svg/ingredients/seaweed.svg
  src/assets/svg/ingredients/taiyaki.svg
  src/assets/svg/ingredients/tofu.svg
  src/components/Mypage/IngredientListItem.tsx
  src/components/Signup/SignupForm.tsx
  src/components/common/Ingredient.tsx
  src/components/common/ReceivedIngredientsList.tsx
  src/components/common/ToastContainer.tsx
  src/components/shared/GuideModal.tsx
  src/components/shared/WelcomModal.tsx
  src/constants/ingredient.ts
  src/pages/MyPage.tsx
  src/pages/RandomUserPage.tsx
  src/pages/SignupPage.tsx
  src/pages/TteokgukCookingPage.tsx
  src/pages/TteokgukPage.tsx
  src/store/auth.ts
  src/store/tteokguk.ts
  src/types/ingredient.ts
  src/types/tteokguk.ts
Labels: ✨ Feature

#51 [#49] Feat: 추가 및 변경된 이미지들 삽입
  src/assets/images/delivery-dragon.png
  src/assets/images/drive-dragon.png
  src/assets/images/header-logo.png
  src/assets/images/home-logo.png
  src/assets/images/shopping-dragon.png
  src/assets/images/try-dragon.png
  src/assets/svg/gift.svg
  src/assets/svg/header-logo.svg
  src/assets/svg/kakao.svg
  src/assets/svg/lucky-bag.svg
  src/assets/svg/tteokguk.svg
  src/components/common/ReceivedIngredientsList.tsx
  src/components/shared/GuideModal.tsx
  src/components/shared/WelcomModal.tsx
  src/pages/EmailLoginPage.tsx
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/pages/TteokgukCookingPage.tsx
Labels: ✨ Feature

#50 [#41] Feat: 로그인 API 연동 작업
  src/apis/auth.ts
  src/apis/core.ts
  src/components/Nickname/NicknameForm.tsx
  src/components/Signup/SignupForm.tsx
  src/pages/EmailLoginPage.tsx
  src/pages/LoginPage.tsx
  src/pages/NicknamePage.tsx
  src/pages/SignupPage.tsx
  src/store/auth.ts
  src/types/auth.ts
  src/types/form.ts
  src/utils/localStorage.ts
Labels: ✨ Feature

#54 [RE: #41] Fix: 잘못 사용하는 상수 변경 (INGREDIENT_NAME_BY_KEY)
  src/pages/NicknamePage.tsx
Labels: 🐞 Bugfix

#57 [#47] Feat: 다른 사용자 페이지 api 함수 구현 및 데이터 렌더
  src/apis/user.ts
  src/components/Nickname/NicknameForm.tsx
  src/components/common/TteokgukImage.tsx
  src/components/common/TteokgukList.tsx
  src/components/common/UserProfileSection.tsx
  src/components/shared/WelcomModal.tsx
  src/pages/MyPage.tsx
  src/pages/NicknamePage.tsx
  src/pages/SignupPage.tsx
  src/pages/UserPage.tsx
  src/routes/Routes.tsx
  src/store/user.ts
  src/types/tteokguk.ts
  src/types/user.ts
  src/utils/jotai.ts
Labels: ✨ Feature

#55 [#39] Feat: 마이페이지 api 함수, atom 구현 및 적용
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/apis/tteokguk.ts
  src/apis/user.ts
  src/components/Mypage/IngredientList.tsx
  src/components/Mypage/IngredientListItem.tsx
  src/components/common/Ingredient.tsx
  src/pages/EmailLoginPage.tsx
  src/pages/MyPage.tsx
  src/pages/TteokgukCookingPage.tsx
  src/pages/TteokgukPage.tsx
  src/pages/UserPage.tsx
  src/store/tteokguk.ts
  src/store/user.ts
  src/types/ingredient.ts
  src/types/tteokguk.dto.ts
  src/types/tteokguk.ts
  src/types/user.dto.ts
  src/types/user.ts
Labels: ✨ Feature

#64 [NO-ISSUE] Feat: build workflow에 secret env 추가
  .github/workflows/deploy-resource.yml
  src/components/shared/WelcomeModal.tsx
  src/pages/NicknamePage.tsx
Labels: ✏️ Modify
