Repository tteokguk-please/tteokguk-frontend, pull requests merged in 2024-02, with the labels that each got.

#67 [#63] Feat: 메인 페이지에 BottomCTA 적용
  src/components/common/BottomCTA.tsx
  src/hooks/useBottomCTA.ts
  src/hooks/useWindowScroll.ts
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
Labels: ✨ Feature

#60 [#48] Feat: 메인 페이지의 탭별 떡국 리스트 무한 스크롤 api 구현 및 토큰 재발급 구현
  package.json
  pnpm-lock.yaml
  src/apis/core.ts
  src/apis/tteokguk.ts
  src/apis/user.ts
  src/components/common/BottomCTA.tsx
  src/components/common/TteokgukList.tsx
  src/components/common/TteokgukWithCaptionList.tsx
  src/hooks/useBottomCTA.ts
  src/hooks/useIntersectionObserver.ts
  src/hooks/useWindowScroll.ts
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/pages/MyActivityPage.tsx
  src/store/tteokguk.ts
  src/store/user.ts
  src/types/tteokguk.dto.ts
  src/types/tteokguk.ts
  src/types/user.dto.ts
  src/utils/array.ts
  src/utils/token.ts
Labels: ✨ Feature

#65 [#61] Feat: 홈 페이지에 패턴과 산 이미지 적용, 404 페이지 UI 구현
  src/assets/images/home-pattern.png
  src/assets/images/left-mountain.png
  src/assets/images/right-mountain.png
  src/components/common/Header.tsx
  src/pages/HomePage.tsx
  src/pages/NotFoundPage.tsx
  src/routes/Routes.tsx
Labels: ✨ Feature

#68 [#66] Feat: 로딩 화면 UI 및 애니메이션 구현
  panda.config.ts
  src/assets/images/ground.png
  src/assets/images/running-dragon.png
  src/components/common/Loading.tsx
Labels: ✨ Feature

#70 [#69] Feat: 떡국 페이지 api 연동
  src/apis/tteokguk.ts
  src/components/common/Ingredient.tsx
  src/pages/TteokgukPage.tsx
  src/store/tteokguk.ts
  src/types/tteokguk.dto.ts
Labels: ✨ Feature

#73 [#72] Feat: 유저 검색 페이지 UI 구현 및 api 연동
  src/apis/user.ts
  src/assets/svg/search.svg
  src/components/common/Header.tsx
  src/pages/EmailLoginPage.tsx
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/pages/MyActivityPage.tsx
  src/pages/MyPage.tsx
  src/pages/NicknamePage.tsx
  src/pages/NotFoundPage.tsx
  src/pages/SearchUserPage.tsx
  src/pages/SignupPage.tsx
  src/pages/TteokgukCookingPage.tsx
  src/pages/TteokgukPage.tsx
  src/pages/UserPage.tsx
  src/routes/Routes.tsx
  src/store/user.ts
  src/types/user.dto.ts
Labels: ✨ Feature

#77 [#76] Feat: 로그인한 유저의 정보 요청 api 함수와 atom 구현 및 적용
  src/apis/user.ts
  src/components/TteokgukPage/Ingredient.tsx
  src/components/common/BottomCTA.tsx
  src/components/shared/AddIngredientsModal.tsx
  src/constants/ingredient.ts
  src/hooks/useBottomCTA.ts
  src/pages/TteokgukCookingPage.tsx
  src/pages/TteokgukPage.tsx
  src/store/tteokguk.ts
  src/store/user.ts
  src/types/tteokguk.dto.ts
  src/types/user.dto.ts
Labels: ✨ Feature

#88 [#85] Fix: 배포 시 S3에 기존 정적 파일을 제거하도록 변경
  .github/workflows/deploy-resource.yml
Labels: 🐞 Bugfix

#83 [#82] Feat: 유저 탈퇴하기 api와 atom 구현 및 적용
  src/apis/core.ts
  src/apis/user.ts
  src/components/Nickname/NicknameForm.tsx
  src/components/Signup/SignupForm.tsx
  src/hooks/useDialog.tsx
  src/pages/MyPage.tsx
  src/pages/SignupPage.tsx
  src/store/user.ts
  src/types/auth.ts
  src/types/dialog.ts
  src/utils/localStorage.ts
Labels: ✨ Feature

#93 [#84] Feat: ProtectedRoute 구현
  src/routes/ProtectedRoute.tsx
  src/routes/Routes.tsx
Labels: ✨ Feature

#86 [#81] Feat: 떡국 삭제 api와 atom 구현 및 적용
  src/apis/tteokguk.ts
  src/pages/TteokgukPage.tsx
  src/store/tteokguk.ts
Labels: ✨ Feature

#96 [#94] Feat: refresh token 만료시 로컬 스토리지 삭제
  src/apis/core.ts
  src/pages/NicknamePage.tsx
  src/routes/ProtectedRoute.tsx
  src/types/auth.ts
Labels: ✨ Feature

#91 [#90] Feat: 로그아웃 구현
  src/pages/MyPage.tsx
Labels: ✨ Feature

#95 [#87] Feat: 랜덤 방문 api 구현 및 적용
  src/apis/user.ts
  src/pages/MyPage.tsx
  src/pages/UserPage.tsx
  src/store/user.ts
  src/types/user.dto.ts
Labels: ✨ Feature

#99 [NO-ISSUE] Fix: kakao login 엣지 케이스 예외 처리
  src/main.tsx
  src/pages/LoginPage.tsx
  src/routes/ProtectedRoute.tsx
Labels: 🐞 Bugfix

#100 [#98] Feat: open graph 설정
  index.html
  public/assets/thumbnail.png
Labels: ✨ Feature

#97 [#89] Feat: 에러 화면 구현 및 적용
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/assets/images/error.png
  src/assets/images/not-found.png
  src/assets/lottie/loading.json
  src/components/common/Button.tsx
  src/components/common/LoadingLottie.tsx
  src/pages/ErrorFallbackPage.tsx
  src/pages/MainPage.tsx
  src/pages/MyPage.tsx
  src/pages/NotFoundPage.tsx
  src/pages/TteokgukCookingPage.tsx
  src/pages/TteokgukPage.tsx
  src/pages/UserPage.tsx
  src/store/tteokguk.ts
  src/store/user.ts
Labels: ✨ Feature

#79 [#78] Feat: 활동 내역에서 받은 재료 리스트를 가져오는 api와 atom 구현 및 적용
  src/apis/myActivity.ts
  src/components/common/DialogModal.tsx
  src/components/common/ReceivedIngredientsList.tsx
  src/pages/MyActivityPage.tsx
  src/store/myActivity.ts
  src/types/myActivity.dto.ts
  src/types/myActivity.ts
Labels: ✨ Feature

#106 [#104] Fix: 이미지 로드 전, 공간 차지하도록 수정
  index.html
  public/assets/favicon.ico
  src/pages/EmailLoginPage.tsx
  src/pages/LoginPage.tsx
  src/pages/TteokgukCookingPage.tsx
Labels: 🐞 Bugfix

#105 [#80] Feat: 내가 응원한 떡국 api 적용
  src/apis/myActivity.ts
  src/components/MyActivity/MySupportedTteokgukCardList.tsx
  src/components/TteokgukCookingPage/Ingredient.tsx
  src/components/common/BottomCTA.tsx
  src/components/common/ReceivedIngredientsList.tsx
  src/pages/MainPage.tsx
  src/pages/MyActivityPage.tsx
  src/pages/TteokgukPage.tsx
  src/store/myActivity.ts
  src/types/myActivity.dto.ts
  src/types/myActivity.ts
Labels: ✨ Feature

#108 [#107] Feat: InfiniteQuery 사용 페이지 fallback 컴포넌트 적용
  src/components/common/Loading.tsx
  src/pages/MainPage.fallback.tsx
  src/pages/MainPage.tsx
  src/pages/MyActivityPage.fallback.tsx
  src/pages/MyActivityPage.tsx
  src/routes/Routes.tsx
  src/store/myActivity.ts
Labels: ✨ Feature

#111 [#110] Fix: 모바일 대응 메타 태그 추가
  index.html
Labels: 🐞 Bugfix

#113 [#112] Modify: 로그인, 로그아웃시 떡국 리스트 invalidate
  src/pages/MyPage.tsx
  src/store/auth.ts
Labels: 🐞 Bugfix

#115 [#114] Fix: 브라우저별 UI 대응
  src/components/MyActivity/MySupportedTteokgukCardList.tsx
  src/pages/EmailLoginPage.tsx
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/pages/MyActivityPage.tsx
  src/pages/MyPage.tsx
  src/pages/TteokgukPage.tsx
Labels: 🐞 Bugfix

#119 [#117] Fix: 재료 추가 모달 이슈 수정
  src/components/TteokgukCookingPage/Ingredient.tsx
  src/components/common/ReceivedIngredientsList.tsx
  src/components/shared/CreateCheerMessageModal.tsx
  src/components/shared/SendIngredientToOthersTteokgukModal.tsx
  src/pages/TteokgukPage.tsx
  src/store/ingredient.ts
  src/types/myActivity.ts
Labels: 🐞 Bugfix

#123 [#121] Feat: 랜덤 떡국 방문 구현 및 떡국 제작 성공 모달 구현
  src/apis/core.ts
  src/apis/tteokguk.ts
  src/assets/svg/activity.svg
  src/assets/svg/big-activity.svg
  src/assets/svg/small-activity.svg
  src/components/common/TteokgukImage.tsx
  src/components/shared/GuideModal.tsx
  src/components/shared/SuccessfulTteokgukCreationModal.tsx
  src/components/shared/WelcomeModal.tsx
  src/pages/EmailLoginPage.tsx
  src/pages/MyPage.tsx
  src/pages/TteokgukCookingPage.tsx
  src/pages/TteokgukPage.tsx
  src/store/tteokguk.ts
  src/types/myActivity.ts
  src/types/tteokguk.dto.ts
  src/types/tteokguk.ts
Labels: 🐞 Bugfix, ✨ Feature

#128 [#127] Feat: 재료 추가 성공 모달 연결 및 api 추가
  index.html
  public/assets/thumbnail.png
  src/apis/tteokguk.ts
  src/components/shared/AddIngredientsToMyTteokgukModal.tsx
  src/components/shared/CreateCheerMessageModal.tsx
  src/components/shared/SuccessfulTteokgukCreationModal.tsx
  src/index.css
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/pages/TteokgukPage.tsx
  src/routes/Routes.tsx
  src/store/tteokguk.ts
Labels: 🐞 Bugfix, ✨ Feature

#130 [#129] Feat: 마이페이지, 유저 페이지의 헤더에 홈 아이콘 추가
  src/apis/core.ts
  src/assets/images/left-mountain.png
  src/assets/svg/home.svg
  src/components/common/Header.tsx
  src/components/common/ReceivedIngredientsList.tsx
  src/components/shared/AddIngredientsModal.tsx
  src/components/shared/AddIngredientsToMyTteokgukModal.tsx
  src/components/shared/CreateCheerMessageModal.tsx
  src/pages/HomePage.tsx
  src/pages/MyPage.tsx
  src/pages/TteokgukPage.tsx
  src/pages/UserPage.tsx
  src/store/auth.ts
  src/store/tteokguk.ts
  src/store/user.ts
Labels: ✨ Feature

#133 [#132] Fix: 로그인 전 내 정보 요청 에러 수정
  src/apis/core.ts
  src/assets/svg/big-activity.svg
  src/store/auth.ts
Labels: 🐞 Bugfix

#135 [#134] Feat: 데이터 없는 경우 UI 구현
  src/pages/MainPage.tsx
  src/pages/MyActivityPage.tsx
  src/pages/MyPage.tsx
  src/pages/UserPage.tsx
Labels: ✨ Feature

#138 [#137] Feat: 닉네임 설정 페이지 진입시 토스트 알림 추가
  index.html
  package.json
  pnpm-lock.yaml
  src/pages/NicknamePage.tsx
Labels: ✨ Feature

#139 [NO-ISSUE] Fix: 탭 이동 시라우팅 적용 및 새로고침 시 탭 유지 구현
  src/pages/MainPage.fallback.tsx
  src/pages/MainPage.tsx
  src/pages/MyActivityPage.fallback.tsx
  src/pages/MyActivityPage.tsx
Labels: ✨ Feature

#140 [NO-ISSUE] Fix: tteokguk detail page 흰 화면 에러 해결
  src/pages/TteokgukPage.fallback.tsx
  src/pages/TteokgukPage.tsx
  src/routes/Routes.tsx
  src/store/tteokguk.ts
  src/store/user.ts
Labels: 🐞 Bugfix

#142 [#141] Fix: 필요하지 않은 재료이면 cursor 허용안함
  src/components/TteokgukCookingPage/Ingredient.tsx
  src/components/common/Header.tsx
  src/pages/HomePage.tsx
  src/pages/MainPage.fallback.tsx
  src/pages/MainPage.tsx
  src/pages/MyActivityPage.fallback.tsx
Labels: 🐞 Bugfix

#143 [NO-ISSUE] Fix: home button
  src/pages/MyPage.tsx
  src/pages/TteokgukPage.tsx
  src/pages/UserPage.tsx
Labels: ✨ Feature

#145 [NO-ISSUE] Fix: $selectedIngredient 초기화 잘 되도록 수정
  src/components/shared/AddIngredientsToMyTteokgukModal.tsx
  src/components/shared/SendIngredientToOthersTteokgukModal.tsx
Labels: 🐞 Bugfix

#144 [#136] Feat: google analytics 추가
  .github/workflows/deploy-resource.yml
  package.json
  pnpm-lock.yaml
  src/components/common/Header.tsx
  src/components/common/TteokgukWithCaptionList.tsx
  src/pages/EmailLoginPage.tsx
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/pages/MyActivityPage.tsx
  src/pages/MyPage.tsx
  src/pages/NicknamePage.tsx
  src/pages/SearchUserPage.tsx
  src/pages/SignupPage.tsx
  src/pages/TteokgukCookingPage.tsx
  src/pages/TteokgukPage.tsx
  src/pages/UserPage.tsx
  vite.config.ts
Labels: ✨ Feature

#148 [#147] Fix: 재료 보내기 할때 필요한 재료가 아니라면 업데이트 안되도록 수정
  src/components/Signup/SignupForm.tsx
  src/components/shared/AddIngredientsToMyTteokgukModal.tsx
  src/components/shared/SendIngredientToOthersTteokgukModal.tsx
  src/pages/MainPage.fallback.tsx
  src/pages/MyActivityPage.fallback.tsx
  src/pages/TteokgukPage.tsx
Labels: 🐞 Bugfix

#150 [#131] Feat: 페이지 검색 최적화
  package.json
  pnpm-lock.yaml
  src/main.tsx
  src/pages/EmailLoginPage.tsx
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/pages/Meta.tsx
  src/pages/MyActivityPage.tsx
  src/pages/MyPage.tsx
  src/pages/NicknamePage.tsx
  src/pages/SearchUserPage.tsx
  src/pages/SignupPage.tsx
  src/pages/TteokgukCookingPage.tsx
  src/pages/TteokgukPage.tsx
  src/pages/UserPage.tsx
Labels: ✨ Feature

#152 [#151] Feat: 재료 클릭시 모달 렌더, 공유하기 링크 기능 추가
  panda.config.ts
  src/apis/tteokguk.ts
  src/assets/svg/home.svg
  src/assets/svg/ingredients-28/beef.svg
  src/assets/svg/ingredients-28/candy.svg
  src/assets/svg/ingredients-28/dumpling.svg
  src/assets/svg/ingredients-28/egg.svg
  src/assets/svg/ingredients-28/fish-cake.svg
  src/assets/svg/ingredients-28/garlic.svg
  src/assets/svg/ingredients-28/green-onion.svg
  src/assets/svg/ingredients-28/index.ts
  src/assets/svg/ingredients-28/mushroom.svg
  src/assets/svg/ingredients-28/rice-cake.svg
  src/assets/svg/ingredients-28/seaweed.svg
  src/assets/svg/ingredients-28/taiyaki.svg
  src/assets/svg/ingredients-28/tofu.svg
  src/components/common/Ingredient.tsx
  src/components/common/UserProfileSection.tsx
  src/components/shared/CheerSuccessModal.tsx
  src/components/shared/CreateCheerMessageModal.tsx
  src/components/shared/SendIngredientToOthersTteokgukModal.tsx
  src/components/shared/ViewMessageModal.tsx
  src/constants/ingredient.ts
  src/pages/MyPage.tsx
  src/pages/TteokgukPage.tsx
  src/pages/UserPage.tsx
  src/store/tteokguk.ts
  src/types/tteokguk.dto.ts
  src/utils/linkShare.ts
Labels: ✨ Feature

#154 [#153] Feat: 보낸 메시지 모달에서 메시지 위에 보낸 이 추가
  src/components/shared/ViewMessageModal.tsx
  src/utils/linkShare.ts
Labels: ✨ Feature

#156 [#155] Fix: 재료 선택시 search params 소문자로 수정
  src/components/shared/CheerSuccessModal.tsx
  src/components/shared/ViewMessageModal.tsx
  src/pages/TteokgukPage.tsx
  src/store/auth.ts
  src/store/user.ts
Labels: 🐞 Bugfix
